### ISSUE TITLE
Not respecting default when attr type Erlen::Schema::ArrayOf

### ISSUE THREAD

**Issue by goleksiak** [Hireology/erlen#41]
Given this attribute definition in a schema:
```
attribute :membership_organization_ids, Erlen::Schema::ArrayOf.new(Integer), default: nil
```
Erlen will set a default of: [] in
```
::Identity::UserUpdateSchema.import(role_id: 1)
```
![image](https://user-images.githubusercontent.com/15343/31503327-57b307d6-af3d-11e7-9d6a-02d09d0d8076.png)

**Comment by arlandism** [comment]
@goleksiak Can I close this?
