### ISSUE TITLE
Update simplecov for ruby 2.4 >= compatibility

### ISSUE THREAD

**Issue by arlandism** [Hireology/erlen#54]
Simplecov 0.12.0 still uses Fixnum, which went away in 2.4 It looks like [0.13.0 supports Ruby 2.4](https://github.com/colszowka/simplecov/issues/544), but we may as well update to the latest if there are no blockers to doing that.

**Comment by iande** [comment]
I believe this was addressed by #57

**Comment by arlandism** [comment]
👍
